"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REFUSED_STATUS = exports.ON_ATTEMPT_STATUS = exports.VALIDATED_STATUS = exports.SUPER_ADMIN_USER_TYPE_ID = exports.BLOCKED_USER_USER_TYPE_ID = exports.USER_USER_TYPE_ID = exports.ADMIN_USER_TYPE_ID = exports.DEV_USER_TYPE_ID = void 0;
exports.DEV_USER_TYPE_ID = 1;
exports.ADMIN_USER_TYPE_ID = 2;
exports.USER_USER_TYPE_ID = 3;
exports.BLOCKED_USER_USER_TYPE_ID = 4;
exports.SUPER_ADMIN_USER_TYPE_ID = 5;
exports.VALIDATED_STATUS = 4;
exports.ON_ATTEMPT_STATUS = 5;
exports.REFUSED_STATUS = 6;
